[wokwi]
version = 1
firmware = "firmware/freertos_apps/microros_esp32_extensions/build/esp32_controller_sim.bin"
elf = "firmware/freertos_apps/microros_esp32_extensions/build/esp32_controller_sim.elf"